___

<a href="https://medium.com/kaveai"> <img src="https://miro.medium.com/max/1280/1*ZoBBIEgT-n-LSkbmRnKCbw.jpeg" /></a>
___

<div style = "font-size: 20px">
    <h1><center>
        LİNEER REGRESYON : NORMAL DENKLEM
    </center></h1>
</div>

----------------------

In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_excel('Ex2.xlsx')

In [3]:
df = dataset.copy()

In [4]:
df.head()

Size of the House  Number of Bedrooms  Price of the House
0               2104                   3              399900
1               1600                   3              329900
2               2400                   3              369000
3               1416                   2              232000
4               3000                   4              539900

------------------

# PROJEKSİYON

<div style = "font-size: 16px">
   \begin{align}
   X^T Xw ̂=X^T y
   \end{align} 
</div>

<div style = "font-size: 16px">
   \begin{align}
   w ̂=(X^T X)^{-1} X^T y
   \end{align} 
</div>

<div style = "font-size: 16px">
   \begin{align}
   RMSE∶\sqrt[]{(\frac{‖e‖^2}{m})}  
   \end{align} 
</div>

In [5]:
def Projection(X, y):
    m, n     = X.shape
    pseudo_  = np.dot(X.T, X)
    pseudo   = np.linalg.pinv(pseudo_)
    X_       = np.dot(pseudo, X.T)
    w        = np.dot(X_, y)
    y_hat    = np.dot(X, w)
    error_v  = y - y_hat
    RMSE     = np.sqrt((1 / m) * np.sum(np.dot(error_v.T, error_v)))
    return RMSE, w

-----------------

In [6]:
X = df.iloc[:, 0:2].values
X[:10]

array([[2104,    3],
       [1600,    3],
       [2400,    3],
       [1416,    2],
       [3000,    4],
       [1985,    4],
       [1534,    3],
       [1427,    3],
       [1380,    3],
       [1494,    3]], dtype=int64)

In [7]:
y = df.iloc[:, 2:3].values
y[:10]

array([[399900],
       [329900],
       [369000],
       [232000],
       [539900],
       [299900],
       [314900],
       [198999],
       [212000],
       [242500]], dtype=int64)

In [8]:
ones    = np.ones((len(X), 1))
X_total = np.concatenate([ones, X], axis = 1)
X_total[:10]

array([[1.000e+00, 2.104e+03, 3.000e+00],
       [1.000e+00, 1.600e+03, 3.000e+00],
       [1.000e+00, 2.400e+03, 3.000e+00],
       [1.000e+00, 1.416e+03, 2.000e+00],
       [1.000e+00, 3.000e+03, 4.000e+00],
       [1.000e+00, 1.985e+03, 4.000e+00],
       [1.000e+00, 1.534e+03, 3.000e+00],
       [1.000e+00, 1.427e+03, 3.000e+00],
       [1.000e+00, 1.380e+03, 3.000e+00],
       [1.000e+00, 1.494e+03, 3.000e+00]])

In [9]:
cost, weights = Projection(X_total, y)

In [10]:
weights

array([[89597.90954361],
       [  139.21067402],
       [-8738.01911255]])

In [11]:
cost

63926.20824986929